

clean:
	-rm *.log
	-rm *.svf
	-rm *.mr 
	-rm *.ddc
	-rm *.syn
	-rm *.rpt
	-rm Synopsys*.txt
	-rm area_pt
	-rm -r ARCH
	-rm -r ENTI
	-rm -r PACK
	-rm -r alib-52
	-rm -r WORK_autoread
	-rm -r reports

